/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import DAO.Conexion;

/**
 *
 * @author chris
 */
public class User extends javax.swing.JPanel {

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnEntrada = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lvlBienvenido = new javax.swing.JLabel();
        lvlBienvenidoNombre = new javax.swing.JLabel();
        lvlBienvenidoID = new javax.swing.JLabel();
        pnlLinea1 = new javax.swing.JPanel();
        pnlLinea2 = new javax.swing.JPanel();
        lvlBienvenido1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnCerrarSesion2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalida = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrada.setBackground(new java.awt.Color(204, 0, 0));
        btnEntrada.setFont(new java.awt.Font("SimSun-ExtG", 1, 24)); // NOI18N
        btnEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrada.setText("Entrada");
        btnEntrada.setToolTipText("");
        btnEntrada.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true), new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true)));
        jPanel7.add(btnEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 220, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Iconos/iconSalir.png"))); // NOI18N
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        lvlBienvenido.setBackground(new java.awt.Color(255, 0, 0));
        lvlBienvenido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lvlBienvenido.setForeground(new java.awt.Color(255, 0, 0));
        lvlBienvenido.setText("ID: ");
        jPanel7.add(lvlBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        lvlBienvenidoNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lvlBienvenidoNombre.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.add(lvlBienvenidoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 200, 40));

        lvlBienvenidoID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lvlBienvenidoID.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.add(lvlBienvenidoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 80, 40));

        pnlLinea1.setBackground(new java.awt.Color(255, 0, 0));
        pnlLinea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        javax.swing.GroupLayout pnlLinea1Layout = new javax.swing.GroupLayout(pnlLinea1);
        pnlLinea1.setLayout(pnlLinea1Layout);
        pnlLinea1Layout.setHorizontalGroup(
            pnlLinea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );
        pnlLinea1Layout.setVerticalGroup(
            pnlLinea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel7.add(pnlLinea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 360, 10));

        pnlLinea2.setBackground(new java.awt.Color(255, 0, 0));
        pnlLinea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        javax.swing.GroupLayout pnlLinea2Layout = new javax.swing.GroupLayout(pnlLinea2);
        pnlLinea2.setLayout(pnlLinea2Layout);
        pnlLinea2Layout.setHorizontalGroup(
            pnlLinea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );
        pnlLinea2Layout.setVerticalGroup(
            pnlLinea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel7.add(pnlLinea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 90, -1));

        lvlBienvenido1.setBackground(new java.awt.Color(255, 0, 0));
        lvlBienvenido1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lvlBienvenido1.setForeground(new java.awt.Color(255, 0, 0));
        lvlBienvenido1.setText("Bienvenido: ");
        jPanel7.add(lvlBienvenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 650));

        jPanel8.setBackground(new java.awt.Color(204, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion2.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion2.setFont(new java.awt.Font("SimSun-ExtG", 1, 24)); // NOI18N
        btnCerrarSesion2.setForeground(new java.awt.Color(204, 0, 0));
        btnCerrarSesion2.setText("Cerrar Sesion");
        btnCerrarSesion2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true)));
        jPanel8.add(btnCerrarSesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 180, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Iconos/iconEntrar.png"))); // NOI18N
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 50, 60));

        btnSalida.setBackground(new java.awt.Color(255, 255, 255));
        btnSalida.setFont(new java.awt.Font("SimSun-ExtG", 1, 24)); // NOI18N
        btnSalida.setForeground(new java.awt.Color(204, 0, 0));
        btnSalida.setText("Salida");
        btnSalida.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true)));
        jPanel8.add(btnSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 220, 80));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 0, 490, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrarSesion2;
    public javax.swing.JButton btnEntrada;
    public javax.swing.JButton btnSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lvlBienvenido;
    private javax.swing.JLabel lvlBienvenido1;
    public javax.swing.JLabel lvlBienvenidoID;
    public javax.swing.JLabel lvlBienvenidoNombre;
    private javax.swing.JPanel pnlLinea1;
    private javax.swing.JPanel pnlLinea2;
    // End of variables declaration//GEN-END:variables
}
